### ISSUE TITLE
Create Profile page

### ISSUE THREAD

**Issue by alenamedved** [alenamedved/Reddish-Egret-Practicum#11]
Should be able to write to Firebase/
Atributes:
Image,
Location,
Languages,
Country of origin (selector drop down to chose from all countries),
Textfield: tell about yourself,
Hobbies/interests: list of things to chose from / drop down 
Social media profiles to share: input link to social media (FB, Insta, Twitter, etc)
Age, gender, kids, single/married

**Comment by avspeed** [comment]
@alenamedved  @UmaRamasamy @tadesse123  mui has an example with a country autocomplete drop down list.
The same example can be used for the other drop downs

https://mui.com/components/autocomplete/

https://stackblitz.com/edit/react-vg2ipm?file=demo.js
