### ISSUE TITLE
Add new post button inside the Header

### ISSUE THREAD

**Issue by alenamedved** [alenamedved/Reddish-Egret-Practicum#30]
write new post to data base inside 'posts' collection

**Comment by alenamedved** [comment]
@UmaRamasamy not necessarily inside the header. And we you can do a popup window, what do you think?

**Comment by UmaRamasamy** [comment]
Yes, we can do that

**Comment by alenamedved** [comment]
functionality added, decided to add 'new post button' outside of Header
